// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YanOverseer.DAL;

namespace YanOverseer.DAL.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200726114055_InitCrate")]
    partial class InitCrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("YanOverseer.DAL.Models.GuildSettings", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoLogCreateMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoLogDeleteMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoLogUpdateMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoRoleName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoWelcomeMessage")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CreateMessageChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DeleteMessageChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeratorRoleName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UpdateMessageChannel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("YanOverseer.DAL.Models.Message", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("YanOverseer.DAL.Models.Profile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountMessageWithImage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountMessageWithUrl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountTextMessage")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("YanOverseer.DAL.Models.Message", b =>
                {
                    b.HasOne("YanOverseer.DAL.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
